#!/usr/bin/env python3
"""
Regenerate the app grid in index.html from the folders in this directory.

Drop this file in the root of the Apps repo (next to index.html) and run:

    python3 build-index.py

It finds every subdirectory that contains an index.html, and rewrites the
links inside the .app-grid div. Everything else in index.html -- the styles,
the heading, the head tag -- is left untouched, so you can keep editing the
page by hand.

Flags:
    --dry-run   print the generated block, don't write the file
    --check     exit 1 if index.html is out of date (useful in CI)
"""

import argparse
import html
import re
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent
INDEX = ROOT / "index.html"

START = "<!-- APPS:START - generated by build-index.py, do not edit by hand -->"
END = "<!-- APPS:END -->"

# Folders to ignore even if they contain an index.html.
SKIP = {".git", ".github", "node_modules", "assets", "vendor", "docs", "shared"}

# Optional pretty names. Any folder not listed here uses its own name.
# Add entries as you build new apps.
LABELS = {
    "Timer": "⏱ Timer",
    "PacMan": "🟡 Pac-Man",
    "ChessTimer": "♟ Chess Timer",
    "Cars": "🚗 Cars",
    "Checklist": "✅ Checklist",
    "Workout Timer": "🏋 Workout Timer",
    "WorkoutTimer2": "🏋 Workout Timer 2",
    "WorkoutTimer3": "🏋 Workout Timer 3",
    "WorkoutTimer4": "🏋 Workout Timer 4",
}


def discover_apps():
    """Every immediate subdirectory holding an index.html, sorted case-insensitively."""
    apps = []
    for path in sorted(ROOT.iterdir(), key=lambda p: p.name.lower()):
        if not path.is_dir() or path.name.startswith(".") or path.name in SKIP:
            continue
        if not (path / "index.html").exists():
            print(f"  skip: {path.name}/ has no index.html", file=sys.stderr)
            continue
        apps.append(path.name)
    return apps


def render(apps):
    """Build the block of anchor tags, matching the existing markup style."""
    lines = [f"      {START}"]
    for name in apps:
        # quote() percent-encodes spaces so "Workout Timer/" resolves on Pages.
        href = quote(name) + "/"
        label = html.escape(LABELS.get(name, name))
        lines.append(f'      <a class="app-button" href="{href}">{label}</a>')
    lines.append(f"      {END}")
    return "\n".join(lines)


def splice(source, block):
    """Insert the block, using the markers if present or the app-grid div if not."""
    if START in source and END in source:
        pattern = re.compile(
            re.escape(START) + r".*?" + re.escape(END), re.DOTALL
        )
        # Strip the leading indent we added; it is already in the source.
        return pattern.sub(block.strip(), source, count=1)

    grid = re.compile(
        r'(<div class="app-grid">)(.*?)(\n\s*</div>)', re.DOTALL
    )
    if not grid.search(source):
        sys.exit(
            'error: no <div class="app-grid"> found in index.html.\n'
            "        Add one, or paste the APPS:START / APPS:END markers where\n"
            "        you want the links generated."
        )
    return grid.sub(lambda m: m.group(1) + "\n" + block + m.group(3), source, count=1)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not INDEX.exists():
        sys.exit(f"error: {INDEX} not found. Run this from the repo root.")

    apps = discover_apps()
    if not apps:
        sys.exit("error: found no app folders. Nothing to do.")

    lowered = [a.lower() for a in apps]
    for name in apps:
        if lowered.count(name.lower()) > 1:
            print(
                f"  warning: {name}/ collides with another folder that differs"
                " only in case",
                file=sys.stderr,
            )

    source = INDEX.read_text(encoding="utf-8")
    updated = splice(source, render(apps))

    if args.dry_run:
        print(render(apps))
        return

    if args.check:
        if updated != source:
            print("index.html is out of date. Run: python3 build-index.py")
            sys.exit(1)
        print("index.html is up to date.")
        return

    if updated == source:
        print(f"index.html already lists all {len(apps)} apps. No change.")
        return

    INDEX.write_text(updated, encoding="utf-8")
    print(f"Updated index.html with {len(apps)} apps:")
    for name in apps:
        print(f"  - {name}")


if __name__ == "__main__":
    main()
